language: node_js
node_js:
  - '10'
env:
  - EXTENSION_ID=ohfjpkccecpdfkpmfocndhepolhljfhg
script: echo "No test"
deploy:
  provider: script
  script: npm run release
  on:
    branch: master
    tags: true
